### ISSUE TITLE
PC 端小程序公告提示文案被吃掉了一截，不知道是不是微信限制

### ISSUE THREAD

**Issue by imgradeone** [RockChinQ/camwall-docs#1]
微信版本：微信 for Windows 3.6.0.18

![image](https://user-images.githubusercontent.com/30969327/166129334-7eb66890-6a4f-4a05-bbed-4e12e23cd15b.png)

**Comment by RockChinQ** [comment]
应该是微信客户端问题，手机上没有此情况
